# -*- coding: utf-8 -*-
"""EDA saham Telkom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrHNa5ACV1aKDuKoGIT2PSBNISnES9MV
"""

import pandas as pd
import numpy as np
import seaborn as sns

path_dataset = "/content/TLKM.csv"

data = pd.read_csv(path_dataset)

data.head()

data.tail()

data.shape

data.describe()

data.columns

data.nunique()

data['low'].unique()

data['weight_for_index'].unique()

#Cleaning Data

data.isnull().sum()

data.drop('delisting_date',axis=1,inplace=True)

data.head()

data.isnull().sum()

TLKM = data.drop(['date', 'index_individual', 'offer', 'offer_volume', 'bid', 'bid_volume', 'listed_shares', 'tradeble_shares', 'weight_for_index', 'foreign_sell', 'foreign_buy', 'non_regular_volume', 'non_regular_value', 'non_regular_frequency'], axis=1)

TLKM.head()

#Relationship Analysis

corelation = TLKM.corr()

sns.heatmap(corelation, xticklabels=corelation.columns, yticklabels=corelation.columns, annot=True)

sns.pairplot(TLKM)

sns.relplot(x='high', y='low', hue='open_price', data=TLKM)

sns.displot(TLKM['low'])

sns.histplot(TLKM['close'])

sns.catplot(x='low', kind='box', data=TLKM)